CREATE TABLE [dbo].[Currency]
(
	[Id] NVARCHAR(65) UNIQUE NOT NULL DEFAULT (NEWID()),
	[Name] NVARCHAR(50) NOT NULL,
	[Code] NVARCHAR(5) NOT NULL,
	[Symbol] NVARCHAR(5) NOT NULL,
	CONSTRAINT [PK_Currency_Id] PRIMARY KEY ([Id] ASC)
)
