CREATE TABLE [dbo].[Role]
(
	[Id] NVARCHAR(65) UNIQUE NOT NULL DEFAULT (NEWID()),
	[Name] NVARCHAR(50) NOT NULL,
	[IsForStaff] BIT NOT NULL DEFAULT 0,
	[CreatedById] NVARCHAR(65) DEFAULT NULL,
	[Description] NVARCHAR(200) DEFAULT NULL,
	[CreatedOn] DATETIME2(7) NOT NULL DEFAULT (GETDATE()),
	CONSTRAINT [PK_Role_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_Role_Account_CreatedById] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[Account] ([Id])
)
